### ISSUE TITLE
Feature Request - mount location

### ISSUE THREAD

**Issue by poudenes** [jcwillox/hass-auto-backup#1]
GREAT ADDON!!!!

I would like to see a option where you can mount a location first (for me a webdav)

mount /home/stack

then backup will start and store it to a given location (for me):

/home/stack/backup-ha/

when backup is done umount the location

I know the backups will not shown in HA but all backups are stored save elsewhere, when system crash, or ssd/hdd/sdcard will be corrupt you always have your backups save.

**Comment by jcwillox** [comment]
Thanks!

That's a great idea, I'll probably add `backup_path` parameter that will copy the backup to that location after it is created.

Mount and unmounting may be a little out of scope, I don't think there would be any issues leaving the drive mounted. But you could use the `shell_command` component to unmount and mount the drive.

**Comment by poudenes** [comment]
Yes already had same idea. With a delay in action that will help also.
The backup_path will be great feature also !!!

**Comment by jcwillox** [comment]
Slightly more difficult than expected, when using Home Assistant on docker integrations do not have access to the `/backup` directory, _but they can access `/share`, `/config` `/ssl`_. 

So a simple copy was not an option. The only way to get a copy of the backup is to download it from the Hass.io API. In testing, this is actually very quick. But a lack of access to the `/backup` folder may cause some roadblocks in the future.
