### ISSUE TITLE
Your great integration is, since 0.107.0bx, causing that the Supervisor tab is not shown anymore

### ISSUE THREAD

**Issue by NicoSomerwil** [jcwillox/hass-auto-backup#10]
Hi there, 

First thanks for your great and very useful integration! Right now some users (like me) are experiencing an issue that after an update to 0.1070bx the Supervisor tab has disappeared.

Uninstalling your integration solves this issue. 
Notice some recent 'chats' within the 'beta' HA channel on Discord.

Hopefully you will take a look at this issue. Thanks in advance!

**Comment by jcwillox** [comment]
Wow yeah, I just looked at my beta instance and noticed the supervisor tab was missing.

I've done some testing and found a solution for it by adding `hassio` to `after_dependencies` in the manifest. To be honest, I have no idea why this is the solution, but I was planning on removing the requirement for the `hassio` component, regardless, seeing as its barely used by Auto Backup.

Thanks for bringing this to my attention so I can get an update out before the release 👍 . 

Fixed `manifest.json`.
```json
{
  "domain": "auto_backup",
  "name": "Auto Backup",
  "documentation": "https://github.com/jcwillox/hass-auto-backup",
  "dependencies": ["hassio"],
  "codeowners": ["@jcwillox"],
  "requirements": [],
  "after_dependencies": ["hassio"]
}
```

**Comment by NicoSomerwil** [comment]
You are the best!!!!
Thanks for your quick and helpful reply! 
Best Regards,
Nico
    	
    	

    	
    
  




On Tue, Mar 17, 2020 at 12:27 PM +0100, "Josh Willox" <notifications@github.com> wrote:
















Wow yeah, I just looked at my beta instance and noticed the supervisor tab was missing.



I've done some testing and found a solution for it by adding hassio to after_dependencies in the manifest. To be honest, I have no idea why this is the solution, but I was planning on removing the requirement for the hassio component, regardless, seeing as its barely used by Auto Backup.



Thanks for bringing this to my attention so I can get an update out before the release 👍 .



Fixed manifest.json.

{

  "domain": "auto_backup",

  "name": "Auto Backup",

  "documentation": "https://github.com/jcwillox/hass-auto-backup",

  "dependencies": ["hassio"],

  "codeowners": ["@jcwillox"],

  "requirements": [],

  "after_dependencies": ["hassio"]

}

**Comment by jcwillox** [comment]
@balloob @NicoSomerwil just a heads up, this is now fixed in the [`0.5.0`](https://github.com/jcwillox/hass-auto-backup/releases/tag/0.5.0) release 👍 .

**Comment by balloob** [comment]
So I tracked it down and it was a mistake in the hassio integration. Fix will be in 107 https://github.com/home-assistant/core/pull/32922. I have removed the blacklist too.

**Comment by balloob** [comment]
You should be able to remove hassio again from after deps.

**Comment by jcwillox** [comment]
Perfect! thanks so much.
