### ISSUE TITLE
ENhancement request, possibility to change compression scheme

### ISSUE THREAD

**Issue by gurkburk76** [jcwillox/hass-auto-backup#100]
I'm currently backing up stuff like influxdb data and from what i can tell the build it gz compression is pretty bad compared to zstd or lzma. my influxdb is around 9gb uncompressed and around 4,6gb with standard gz compression, i tried to compress it with 7zip to test lzma and it came down to 2,3gb and 2,6gb with zstd so clearly there is a lot of space left on the table as things as per default in HA.

Is this something that be changed with this plugin or would it require a more in-depth change to HA ? ability to adjust both algo and choose speed or max comp would be great.

**Comment by jcwillox** [comment]
Unfortunately, this is not possible at the moment, Auto Backup just tells HA when to create and delete backups, and the supervisor is responsible for actually creating the backups. So it would require internal changes and trying to do it externally would make your backup incompatible with HA's restore functionality.
