### ISSUE TITLE
Error during backup

### ISSUE THREAD

**Issue by davoloko** [jcwillox/hass-auto-backup#104]
### The problem

Hi @jcwillox! Thank you very much for your work. 
Recently I have restored a backup of my home assistant on another computer and, when trying to launch the copy from the integration, I get the following error:

“Error during backup. OpenSSL 3.0’s legacy provider failed to load. This is a fatal error by default, but cryptography supports running without legacy algorithms by setting the environment variable CRYPTOGRAPHY_OPENSSL_NO_LEGACY. If you did not expect this error, you have likely made a mistake with your OpenSSL configuration.”

If I launch the copy manually from HA it works without any problem. Before restoring the backup it was working correctly.

Could you help me? Thank you very much!

### What version of Auto Backup has the issue?

 1.3.2

### What version of Home Assistant are you running?

2023.5.4

### What type of installation are you running?

Home Assistant Supervised

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

2023.05.dev2601

### Anything in the logs that might be useful for us?

```python3
Logger: custom_components.auto_backup
Source: custom_components/auto_backup/__init__.py:187
Integration: Auto Backup (documentation, issues)
First occurred: 29 de mayo de 2023, 02:30:00 (4 occurrences)
Last logged: 02:30:00

Error during backup. OpenSSL 3.0's legacy provider failed to load. This is a fatal error by default, but cryptography supports running without legacy algorithms by setting the environment variable CRYPTOGRAPHY_OPENSSL_NO_LEGACY. If you did not expect this error, you have likely made a mistake with your OpenSSL configuration.. There may be a backup already in progress.
```

**Comment by jcwillox** [comment]
I think this is an issue with HA / your setup, Auto Backup calls the exact same API that home assistant does in practically the same way.

It could be something to do with the version of the supervisor you're running `2023.05.dev2601`, which seems to be a development version, and different to what I'm on (are you on the beta branch?)
![image](https://github.com/jcwillox/hass-auto-backup/assets/39120423/7262f55c-5d4b-4f5a-bf17-62ec040fb814)

**Comment by davoloko** [comment]
Hello, thank you very much for your help! After the supervisor update that was released yesterday it is working properly. Now I have 2023.06.1
I don't know why in the previous one it appeared .dev because I didn't have the active beta.

Thank you very much!
