### ISSUE TITLE
[FR]: Add support for alternative locations

### ISSUE THREAD

**Issue by ceskyDJ** [jcwillox/hass-auto-backup#106]
### Is your feature request related to a problem? Please describe.

When I need to save backups to multiple locations (e.g. 2 remote backup servers), it's not possible using just this integration. The default backup integration can do this but still hasn't got automatic removing feature.

### Describe the solution you'd like

I'd add a way to select target location, like the official backup integration has.

### Additional context

This is how the default backup integration's solution looks like:
![image](https://github.com/jcwillox/hass-auto-backup/assets/48548230/bdb0a14d-89ff-41ad-888f-1cfdf92b57a0)

**Comment by jcwillox** [comment]
Yes, I've been wanting to look into this since they released the feature looks pretty cool, should be easy to add support for it. I've got some time now so I'll see what I can do 👍
