### ISSUE TITLE
[FR]: Add all showed words/phrases to translation

### ISSUE THREAD

**Issue by misa1515** [jcwillox/hass-auto-backup#111]
### Is your feature request related to a problem? Please describe.

Here are overview of words/phrases which can be translated too (when is in en.json)
![1689774584048](https://github.com/jcwillox/hass-auto-backup/assets/61636045/13ca4cd6-301f-41bb-b0dc-338f0049494a)
![1689774584186](https://github.com/jcwillox/hass-auto-backup/assets/61636045/0dc426a3-1a13-4048-bec0-d30cd361ce20)
![1689858543142](https://github.com/jcwillox/hass-auto-backup/assets/61636045/c86ea0db-9528-4664-a510-9b830e8c67c2)

### Describe the solution you'd like

Have those words/phrases in translation file

**Comment by jcwillox** [comment]
**First image**: this text is already translated, into a variety of languages maybe just not in your locale.

**Second image**: this is not from Auto Backup, looks to be "Google Drive Backup" integration, which I have no control over, you may want to open an image for it there.

**Third image**: yes, the sensors `unit` is not currently translated, I don't know how you do that in Home Assistant but I think it may be possible. If anyone knows and wants to link to the relevant documentation please do.

**Comment by jcwillox** [comment]
I'm going to close this for now, I don't have time to add additional translations support right now, but anyone is welcome to contribute additional translations or add support for translating units.
