### ISSUE TITLE
[FR]: Please keep download_path as Option available!

### ISSUE THREAD

**Issue by dafunkydan** [jcwillox/hass-auto-backup#112]
### Is your feature request related to a problem? Please describe.

> ⚠️ Deprecated
> 
> download_path option is deprecated as Home Assistant now supports custom backup locations using the location option. This new option also supports auto-purging backups from the remote location. If enough people still see value in this option I may un-deprecate it.
> 
Please keep download_path alive!

I have all Backups running locally, and additionally copied over to the NAS. 
If the NAS isn't available for whatever reason, i still have the local Backups.
So this is way more flexible.

More: I am using my NAS as Media Share. That gives the Option not only to use it as Backup Location, but as Media Source.
Furthermore, via "File Size Check" i can easily check, if the NAS is available at all, and choose the best Backup-Strategy.

On Top, i won't have every Backup "double" in the Systems Dialog.
I can go for the Local Backup, and if something terrible fails, use the Backups beeing downloaded to the NAS.

### Describe the solution you'd like

Pleas bring back the download_path Option, as it is way more flexible than using HAs!

**Comment by henriklund** [comment]
Almost same type of config for replication to NAS -> I agree that download_path should be retained.

**Comment by jcwillox** [comment]
Fair enough 👍, I wasn't sure if anyone was still using `download_path`, and had a use case that couldn't be covered by the `location` option, which also supported purging, and there's always been a lot of confusion over the it. I'll un-deprecate it shortly, it's good to know I won't be maintaining a feature no one will be using, now that `location` is available 😄.

**Comment by dafunkydan** [comment]
Jippie, glad to hear that, good news to start the Day :-)
While download_path _is_ confusing - once it is set up, there truly are benefits i don't wanna miss. Thankin you very much for undprecating!
