### ISSUE TITLE
Not all files in Config folder are being backed up

### ISSUE THREAD

**Issue by bluemantwo** [jcwillox/hass-auto-backup#12]
Using this for daily backups:  service: auto_backup.snapshot_full
 
Running on Rpi3B+, Hassio, 0.107.7, with version 0.5.0 of auto backup running from HACs.  

In the Config directory, these files are not being backed up:
- secrets.yaml
- scripts.yaml
- intent_scripts.yaml

When I use the backup feature in Hassio itself, all files are backed up just fine.

**Comment by jcwillox** [comment]
duplicate of #8

For some reason, a couple of people are having this issue where some files or folders within the config directory are not being backed up. I still don't believe this is an issue with AutoBackup as Hass.io handles the creation of backups fully and there is no way to exclude specific files or folders from the config directory.

However, this is certainly an odd behaviour considering it is working from the Web UI, this is likely worthy of an issue over at home-assistant/supervisor.

If you can provide the debug log when taking a snapshot with AutoBackup that could be useful to, at the very least ascertain whether AutoBackup is sending all the data correctly.

**Comment by bluemantwo** [comment]
`20-04-05 01:56:11 INFO (MainThread) [supervisor.snapshots] Full-Snapshot e8c976dc start
20-04-05 01:56:11 INFO (MainThread) [supervisor.snapshots] Snapshot e8c976dc store Add-ons
20-04-05 01:56:11 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on core_check_config
20-04-05 01:56:11 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on core_configurator
20-04-05 01:56:11 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on a0d7b954_glances
20-04-05 01:56:11 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on core_duckdns
20-04-05 01:56:11 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on core_ssh
20-04-05 01:56:11 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on core_samba
20-04-05 01:56:11 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_check_config
20-04-05 01:56:11 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_configurator
20-04-05 01:56:11 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_glances
20-04-05 01:56:11 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_samba
20-04-05 01:56:11 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_ssh
20-04-05 01:56:11 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_duckdns
20-04-05 01:56:11 INFO (MainThread) [supervisor.snapshots] Snapshot e8c976dc store folders
20-04-05 01:56:11 INFO (SyncWorker_6) [supervisor.snapshots.snapshot] Snapshot folder share
20-04-05 01:56:11 INFO (SyncWorker_9) [supervisor.snapshots.snapshot] Snapshot folder ssl
20-04-05 01:56:11 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder homeassistant
20-04-05 01:56:11 INFO (SyncWorker_15) [supervisor.snapshots.snapshot] Snapshot folder addons/local
20-04-05 01:56:11 INFO (SyncWorker_6) [supervisor.snapshots.snapshot] Snapshot folder share done
20-04-05 01:56:11 INFO (SyncWorker_15) [supervisor.snapshots.snapshot] Snapshot folder addons/local done
20-04-05 01:56:11 INFO (SyncWorker_9) [supervisor.snapshots.snapshot] Snapshot folder ssl done
20-04-05 01:57:15 WARNING (SyncWorker_4) [supervisor.snapshots.snapshot] Can't snapshot folder homeassistant: [Errno 2] No such file or directory: '/data/homeassistant/home-assistant_v2.db-shm'
20-04-05 01:57:16 INFO (MainThread) [supervisor.snapshots] Full-Snapshot e8c976dc done`

**Comment by bluemantwo** [comment]
That WARNING does correspond to the /homeassistant folder which is what I call the Config folder.  I do not know what that db-shm file is.  Of course, I do have the .db file.

**Comment by bluemantwo** [comment]
And here is what I get when doing the normal full backup from the web interface:

20-04-04 21:55:02 INFO (MainThread) [supervisor.snapshots] Full-Snapshot 364bc8dc start
20-04-04 21:55:02 INFO (MainThread) [supervisor.snapshots] Snapshot 364bc8dc store Add-ons
20-04-04 21:55:02 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on core_duckdns
20-04-04 21:55:02 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on a0d7b954_glances
20-04-04 21:55:02 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on core_check_config
20-04-04 21:55:02 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on core_configurator
20-04-04 21:55:02 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on core_ssh
20-04-04 21:55:02 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on core_samba
20-04-04 21:55:02 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_glances
20-04-04 21:55:02 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_check_config
20-04-04 21:55:02 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_configurator
20-04-04 21:55:02 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_samba
20-04-04 21:55:02 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_ssh
20-04-04 21:55:02 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_duckdns
20-04-04 21:55:02 INFO (MainThread) [supervisor.snapshots] Snapshot 364bc8dc store folders
20-04-04 21:55:02 INFO (SyncWorker_1) [supervisor.snapshots.snapshot] Snapshot folder share
20-04-04 21:55:02 INFO (SyncWorker_17) [supervisor.snapshots.snapshot] Snapshot folder ssl
20-04-04 21:55:02 INFO (SyncWorker_19) [supervisor.snapshots.snapshot] Snapshot folder homeassistant
20-04-04 21:55:02 INFO (SyncWorker_2) [supervisor.snapshots.snapshot] Snapshot folder addons/local
20-04-04 21:55:02 INFO (SyncWorker_1) [supervisor.snapshots.snapshot] Snapshot folder share done
20-04-04 21:55:02 INFO (SyncWorker_2) [supervisor.snapshots.snapshot] Snapshot folder addons/local done
20-04-04 21:55:02 INFO (SyncWorker_17) [supervisor.snapshots.snapshot] Snapshot folder ssl done
20-04-04 21:56:00 INFO (SyncWorker_19) [supervisor.snapshots.snapshot] Snapshot folder homeassistant done
20-04-04 21:56:02 INFO (MainThread) [supervisor.snapshots] Full-Snapshot 364bc8dc done

**Comment by jcwillox** [comment]
Perfect this is exactly what I needed. So just confirming the first snapshot log was when you did a full snapshot with AutoBackup and the second was through the web interface.

The `.db-shm` are like temporary files that are created while the DB is running, and shouldn't be included, from what I've seen Hass.io actively excludes those files, so I'm not sure why it's even trying locate that file.

This seems to add up, the snapshotting process probably snapshots most of the `homeassistant` folder until it hits that warning then stops causing it to miss some files.

I'm going to make an issue over at `home-assistant/supervisor` they may know more about what could cause this. I'm sure you're on the latest version, but what version of the supervisor are you running.

**Comment by bluemantwo** [comment]
Yes, this all sounds correct.  Let me know if there is anything I can test.

**Comment by jcwillox** [comment]
@bluemantwo as I'm sure you know the fix is available now in the latest version of the supervisor, let me know if this has actually fixed the issue so we can finally close this 😄

**Comment by bluemantwo** [comment]
I have been running the 228 version for 48 hours now and doing regular automated backups every 3 hours just as a test.  I finished reviewing all the backups and did not find any issues with any of them.  Certain files such as logs were not backed up, but that is by design.  Everything else backed up correctly.  So I conclude this issue is resolved. 

Thanks again to everyone who contributes to this wonderful community!
