### ISSUE TITLE
Log warnings for deprecated alias

### ISSUE THREAD

**Issue by J4yDubsHome** [jcwillox/hass-auto-backup#129]
### The problem

Logger: homeassistant.helpers.typing
Source: helpers/deprecation.py:206
First occurred: 7:21:30 PM (4 occurrences)
Last logged: 7:21:31 PM

HomeAssistantType was used from auto_backup, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'auto_backup' custom integration
ServiceCallType was used from auto_backup, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.ServiceCall instead, please report it to the author of the 'auto_backup' custom integration
EventType was used from auto_backup, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.Event instead, please report it to the author of the 'auto_backup' custom integration

### What version of Auto Backup has the issue?

 v1.4.1

### What version of Home Assistant are you running?

2024.5.1

### What type of installation are you running?

Home Assistant OS

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

Supervisor 2024.04.4

### Anything in the logs that might be useful for us?

```python3
Logger: homeassistant.helpers.typing
Source: helpers/deprecation.py:206
First occurred: 7:21:30 PM (4 occurrences)
Last logged: 7:21:31 PM

HomeAssistantType was used from auto_backup, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'auto_backup' custom integration
ServiceCallType was used from auto_backup, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.ServiceCall instead, please report it to the author of the 'auto_backup' custom integration
EventType was used from auto_backup, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.Event instead, please report it to the author of the 'auto_backup' custom integration
```

**Comment by stefan-44** [comment]
Same warning as described by J4yDubsHome:

> Logger: homeassistant.helpers.typing
> Quelle: helpers/deprecation.py:206
> Erstmals aufgetreten: 11:26:28 (4 Vorkommnisse)
> Zuletzt protokolliert: 11:26:29
> 
> HomeAssistantType was used from auto_backup, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'auto_backup' custom integration
> ServiceCallType was used from auto_backup, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.ServiceCall instead, please report it to the author of the 'auto_backup' custom integration
> EventType was used from auto_backup, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.Event instead, please report it to the author of the 'auto_backup' custom integration



Versions used:
AutoBackup v1.4.1

HA:
Core 2024.5.2
Supervisor 2024.05.1
Operating System 12.3
Frontend 20240501.1
