### ISSUE TITLE
Feature Request: Exclude Database Specifically

### ISSUE THREAD

**Issue by ghds514** [jcwillox/hass-auto-backup#13]
I hope that this is an appropriate place to make a feature request. In addition to the ability to exclude folders and/or add-ons, I would like to be able to exclude specific files, specifically the home-assistant_v2.db file. As this grows by hundreds of MB per day and as it would not be of concern in the case that I needed to restore a snapshot, I would like to be able to simply omit it in the snapshot process.

**Comment by jcwillox** [comment]
The backup process is handled entirely by the supervisor, this means AutoBackup can control whether the homeassisant directory is backed up but has no control over its contents. 
The best option in your case would be to either purge the database regularly to stop it growing too large or to use an external database such as the MariaDB addon. If you use MariaDB the database is stored separately and can be excluded by excluding `mariadb` from the backup.

**Comment by ghds514** [comment]
Appreciated, thank you.

**Comment by recursiveGecko** [comment]
Hi @jcwillox, could this request be reconsidered now that [support has been added in Supervisor](https://github.com/home-assistant/supervisor/pull/4591)? 

The [supervisor API](https://developers.home-assistant.io/docs/api/supervisor/endpoints#backup) now includes a `homeassistant_exclude_database` parameter which excludes the recorder database from backups.
