### ISSUE TITLE
Manual start of backup

### ISSUE THREAD

**Issue by danlun** [jcwillox/hass-auto-backup#15]
Hi, im quite new on HA but would like to use your Backup integration. Mainly for making it possibel to store on another network unit. I understand its possible to get a copy of the snapshot there. Some questions:
1. Will any purging or other action happen in the /path?
2. I dont need automatic backup (maybe in the future), more do as today, initiate a backup before I do something "stupid" in the system. Can I manually trigger a snapshot, similar way as I do with the std snapshot functionality?
Thx

**Comment by jcwillox** [comment]
Hey, welcome.
I'm assuming you're talking about the `backup_path` parameter. This only downloads the created snapshot to a directory, it will not automatically delete that file, only the originally created snapshot in your `/backup` directory can be automatically deleted. 
Also it's worth noting that it's pretty limited to where you can download the snapshot to, as Home Assistant has limited assess to the file system.

Yes you can manually trigger snapshots by calling the `auto_backup.snapshot_*` services from the Developer Tools panel in the Web UI (if you can't see it you may need to enable admin mode). Though in this case you may be better of just using the Snapshots UI.
One useful option could be to create a script that calls the snapshot service with some default or templated parameters.

Not sure exactly what you mean by "network unit" but it's often easiest to keep your backups in HA.

**Comment by danlun** [comment]
Yes correct the backup_path and just a copy is fine. I run Hassio on Rpi 3+ booting/running from a USB drive directly connected to the Pi. I can work in the Pi directory from my Windows 10 since I have Samba switch on in HA. 
I was thinking of copy with the backup_path to a Synology server i also have in the same network. Would you say that isnt possible by eg putting this is the back_up path: \\Synology_dan\usbshare2\backupper\Homeassistant?
I would need to use the Developer Tool panel since by using the Snapshot UI i dont get this automatic copy to another disk. 
I would need to read and learn about the scripting possibilities then. I assume this is a standard HA functionality?
The "network unit" is this Synology NAS. And i will keep the backup in HA but make this extra copy thanks to your integration automatically if, by any reason, I cant get to the USB disk anymore. I think SD cards user should be even more worried and looking for your solution. :-)

**Comment by danlun** [comment]
Hi again, any comments on my last input?

**Comment by jcwillox** [comment]
Yes, the [scripts](https://www.home-assistant.io/docs/scripts/) are basically a list of service calls the same as you would use in an automation, these can be configured through the UI.

Well, this may be more difficult than you think, as I mentioned Home Assistant has very limited access to the file system, as a result, you can only download snapshots to the `/config` directory and `/share` at least in my testing. So you would likely need to download your snapshots to a subdirectory of `/share` then have a script running to move any files in that directory over to your server. Another option could be to mount a samba share or FTP drive from your server to a folder inside `/share`, but then there's the risk of leaving the backups in the share folder as those files could be included in future backups causing the backup size to grow exponentially (backup-ception).
There may very well be ways to mount an external drive to Home Assistant or give it wider access to the file system (e.g. like possible editing the docker container), I'm just not aware of straight forward methods at the moment. So you may want to look at another solution, I believe there are some Google Drive or FTP based solutions out there. Good luck 👍

**Comment by danlun** [comment]
Great, thx!!!

**Comment by jdesai61** [comment]
I am using supervised install on an Intel NUC.   My homeassistant has an external NFS drive mounted at /mnt/backup. And I can copy files to (with portainer console in homeassistant container) it or use it as a media directory - so I know that the mount works. But when I specify /mnt/backup as backup_dir, I still get an error.  In a supervised install, does this add-on run in "homeassistant" docker container or some other container?

**Comment by jdesai61** [comment]
I have an automated script that mounts an NFS drive on HA startup (in /mnt/backup).  I am successfully using this add-on with backup_path option to copy backups to the NFS mount.
