### ISSUE TITLE
is_hassio is deprecated

### ISSUE THREAD

**Issue by ErikvO** [jcwillox/hass-auto-backup#158]
### The problem

Logger: homeassistant.components.hassio
Source: helpers/deprecation.py:222
integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 9:08:37 PM (3 occurrences)
Last logged: 9:08:37 PM

is_hassio was called from auto_backup, this is a deprecated function which will be removed in HA Core 2025.11. Use homeassistant.helpers.hassio.is_hassio instead, please create a bug report at https://github.com/jcwillox/hass-auto-backup/issues

### What version of Auto Backup has the issue?

1.5.0

### What version of Home Assistant are you running?

2024.11.0

### What type of installation are you running?

Home Assistant OS

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

2024.11.2

**Comment by steps56** [comment]
Same here.
Please fix it soon, as a working backup integration (used by automation daily) is very important.
Thanks in advance.

**Comment by steps56** [comment]
Still no answer 🤔...😪

**Comment by jcwillox** [comment]
I'll get on this today, its not actually breaking the integration is it? It's just the deprecation notice right?

**Comment by ErikvO** [comment]
Correct. For me the backups still run like normal. It is just the deprecation.

**Comment by J4yDubsHome** [comment]
No rush.  You have a year before it's removed.

**Comment by steps56** [comment]
Thanks a lot for fixing/updating 🙋🏼‍♂️.

**Comment by jcwillox** [comment]
The previous update was just for a breaking issue on HA Core, I was postponing this for a bit because it's just a deprecation warning, it also required pinning the minimum version of HA to 2024.11 for auto backup, but it's now fixed in https://github.com/jcwillox/hass-auto-backup/releases/tag/v1.5.3

**Comment by steps56** [comment]
I am using newest Beta HA App... 😉... so no problem to use even newest not official version of HA 😇.

**Comment by ErikvO** [comment]
Hi @jcwillox 
Thanks for the update. I can confirm the warning is no longer present.

**Comment by jcwillox** [comment]
@jeremysherriff 
> Not how deprecation warnings work, and in my opinion should be reverted. This forces everyone to update HA to 2024.11 at the minimum, so those waiting on bug fixes in HA must now also hold back this integration too. There is a reason the deprecation notice gives 12 months to migrate.

I do agree with you and would rather wait, but I'm going to have people asking about it for the next year, so I'd rather just fix it now and just backport any fixes if I really need to, plus it is nicer to not have any warnings. I also can't easily make this backwards compatible which would be the most ideal solution. That's also why I did the [v1.5.2](https://github.com/jcwillox/hass-auto-backup/releases/tag/v1.5.2) release right before I pinned the version in [v1.5.3](https://github.com/jcwillox/hass-auto-backup/releases/tag/v1.5.3).

An alternate way of looking at it is that HA expects everyone to migrate immediately, but gives a grace period in-case it isn't fixed immediately or people don't update the integration immediately. Perhaps waiting a month or two is the happy medium.

**Comment by Otiel** [comment]
> HA core 2025.1 yesterday includes all updateted backup stuff anxbody may need.

@steps56 That is not true, HA 2025.1 doesn't support [generational backups](https://jcwillox.github.io/hass-auto-backup/advanced-examples/#generational-backups) for instance.

**Comment by steps56** [comment]
> > HA core 2025.1 yesterday includes all updateted backup stuff anxbody may need.
> 
> @steps56 That is not true, HA 2025.1 doesn't support [generational backups](https://jcwillox.github.io/hass-auto-backup/advanced-examples/#generational-backups) for instance.

Yes, it does for sure.
All just configuration stuff du keep, skedule and so on even "outside" HA a.s.o.
