### ISSUE TITLE
is_hassio was called from auto_backup

### ISSUE THREAD

**Issue by fmika** [jcwillox/hass-auto-backup#163]
### The problem

is_hassio was called from auto_backup, this is a deprecated function which will be removed in HA Core 2025.11. Use homeassistant.helpers.hassio.is_hassio instead, please create a bug report at https://github.com/jcwillox/hass-auto-backup/issues

### What type of installation are you running?

None

**Comment by GCustom** [comment]
looks like a duplicate of this https://github.com/jcwillox/hass-auto-backup/issues/158
