### ISSUE TITLE
Feature Request: Keep_hours

### ISSUE THREAD

**Issue by simon2k13** [jcwillox/hass-auto-backup#18]
Hi, i run partial snapshots for some of my data every 2 hours.

i would like to keep the snaps only for 12 hours. how can i accomplish that?

**Comment by jcwillox** [comment]
`keep_days` actually allows decimal numbers so you can just enter `keep_days: 0.5` for half a day or 12 hours. This can even do seconds `keep_days: 0.00001`.

**Comment by simon2k13** [comment]
THanks!
