### ISSUE TITLE
Feature Request - Backup only Configuration Files

### ISSUE THREAD

**Issue by poudenes** [jcwillox/hass-auto-backup#2]
Would be so nice to have option to only backup the configuration files.

I tried with : home assistant configuration but then whole HA is in the backup

**Comment by jcwillox** [comment]
This is out of the scope, at least for now. The Auto Backup integration aims to extend the default hassio snapshots feature, and this option isn't exactly possible with hassio snapshot services, it would require writing effectively my own backup method mimicking hassio snapshots (which might an idea to allow non-hassio users to backup their configs).
