### ISSUE TITLE
Home assistant standalone not booting

### ISSUE THREAD

**Issue by zorro59** [jcwillox/hass-auto-backup#21]
The enviroments variables "HASSIO" and "HASSIO_TOKEN" are not available if home assistant was installed using a package manager.

**Comment by jcwillox** [comment]
Would Hass.io (supervisor) even work with this type of installation? Auto Backup relies on Hass.io to create backups.

**Comment by zorro59** [comment]
You are right, it totally makes sense now. Thanks!
