### ISSUE TITLE
Autoback in virtual environment

### ISSUE THREAD

**Issue by Micha70** [jcwillox/hass-auto-backup#22]
I'm trying to use auto_backup in an vritual environment. I'm using homeassitant since a few month, installed on my Pi3b like described here: https://www.home-assistant.io/docs/installation/virtualenv/
Now I installed hass-auto-backup, but get following two errors:
2020-11-15 07:57:58 ERROR (MainThread) [custom_components.auto_backup] Missing HASSIO environment variable. Please check you have Hass.io installed!
2020-11-15 07:57:58 ERROR (MainThread) [homeassistant.setup] Setup failed for auto_backup: Integration failed to initialize

Is it only working if I use it in an installation with HASSIO?

**Comment by jcwillox** [comment]
Yes, Auto Backup tells Hassio or the "Supervisor" to create the backups, and it is required. Auto Backup is more like a proxy that allows you to easily initiate backups from automations/scripts. This is similar to #21.

**Comment by jcwillox** [comment]
Support for Home Assistant Core was added in [1.0.0](https://github.com/jcwillox/hass-auto-backup/releases/tag/1.0.0) 🎉
