### ISSUE TITLE
backup_path not purged

### ISSUE THREAD

**Issue by browetd** [jcwillox/hass-auto-backup#23]
Hello, I have installed hass-auto-backup on hassos V5.5 64 bits.  Everything is working fine except that the backups stored on the backup_path are not purged (the backup path is located on a mounted NFS drive stored on a synology NAS)...  Is this the normal behaviour of the app ?  Any possibility to purge the backup_path as well ? Thanks !

**Comment by jcwillox** [comment]
Oh yeah, that's intended, I'm actually renaming that in the next release to `download_path` as `backup_path` is really counter-intuitive, it just downloads the backup from the supervisor to the path given. Technically it would be possible to have it delete those downloaded backups, however, it complicates the logic a bit. Would we immediately delete it from HA after downloading, or wait and purge it from both locations? Also, there are quite a few potential points for failure and syncing the HA `backup` directory using `rsync` or `rclone` may be a simpler/more-reliable solution, and would still allow you to use the UI to create/remove backups?

**Comment by browetd** [comment]
Based on your comments, I mapped a drive from my PC to the Pi4 and will be able to access that drive offline... So no need to change anything... Thank you for your quick response ...
