### ISSUE TITLE
event 'auto_backup.snapshot_successfull' not fired

### ISSUE THREAD

**Issue by Merangle** [jcwillox/hass-auto-backup#24]
Hello 

It seems that the event 'auto_backup.snapshot_successfull' never fires. 
This prevents to trigger an automation.

However there is a message in the log  
`2020-12-12 17:26:21 INFO (MainThread) [custom_components.auto_backup] Snapshot created successfully; 'Daily backup: Saturday, December 12, 2020' (ed094d68)`

In the tool> event section, when listening on this event, it never happens.

This is working well for the 'failed' event with a message in the log & event triggered.

The automations are the same, just event's name changed.

Can you please have a look ?   

thanks

**Comment by jcwillox** [comment]
The event is working for me, just checking are you listening for `auto_backup.snapshot_successfull` or `auto_backup.snapshot_successful`, there should not be the extra `L`.

**Comment by Merangle** [comment]
Completely right. Sorry for the trouble. 

I didn't see this spelling mistake and I thought that the event available in the developper tool is one of the events in HA. In fact not;  it's only the list of events used in the automations and scripts (as written by me).

Thanks for your help.
