### ISSUE TITLE
Install via HACS not working

### ISSUE THREAD

**Issue by Eratz** [jcwillox/hass-auto-backup#26]
Hi i installed 0.6.0 via HACS, 
After executing automation logs say "homeassistant.exceptions.ServiceNotFound: Unable to find service auto_backup.snapshot_full"
I cant see the Services or the sensor in the Dev tab.
Tried to reinstall and 0.5.2. 

Im running HA 2020.12.2 on a Raspbian pi4 with docker containers and supervisor.

**Comment by jcwillox** [comment]
Did you add [`auto_backup`](https://github.com/jcwillox/hass-auto-backup#configuration) to your configuration.yaml?

**Comment by Eratz** [comment]
Indeed i totaly missed this part ahah.
Sorry for the inconvenience and thank you for your work.
