### ISSUE TITLE
No web ui to config

### ISSUE THREAD

**Issue by nutsofamily** [jcwillox/hass-auto-backup#29]
I get an initial pop up to add my server address, then "Do you want to set up Auto Backup?" no more webui. Only option is time frame backup time out and an option to delete.
After loading your quick link I click through the settings and get "Success!
Created configuration for Auto Backup."

But I dont see a tab to actually configure it?

**Comment by jcwillox** [comment]
Sounds like everything is working correctly,
that's all the config for Auto Backup, you don't need to add any address, just click submit to create the config entry and then if you want you can change the options, backup timeout and auto purge. What were you expecting?

**Comment by nutsofamily** [comment]
Sorry,
  
I thought you could do all the config parameters and option via a ui.
  
It manual entry after that.
  
  
  
  ┈┈┈┈┈┈▕▔╲
  ┈┈┈┈┈┈┈▏▕
  ┈┈┈┈┈┈┈▏▕▂▂▂
  ▂▂▂▂▂▂╱┈▕▂▂▂▏Pete
  ▉▉▉▉▉┈┈┈▕▂▂▂▏
  ▉▉▉▉▉┈┈┈▕▂▂▂▏
  ▔▔▔▔▔▔╲▂▕▂▂▂I     
  

  
  
>

**Comment by jcwillox** [comment]
Please have a look at the [README](https://github.com/jcwillox/hass-auto-backup), Auto Backup will not just automatically start creating backups, its a tool for creating and removing backups via service calls, ideally from an automation, have a look at the [examples](https://github.com/jcwillox/hass-auto-backup#example-automatic-backups) they show how to setup automatic backups. At a basic level, Auto Backup doesn't do anything except from adding 3 service calls.
