### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by poudenes** [jcwillox/hass-auto-backup#3]
I get this error:

```
2019-12-09 11:21:15 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /snapshots/new/full request
2019-12-09 11:21:15 ERROR (MainThread) [custom_components.auto_backup] Error on Hass.io API: 
```

The backup is still running and finished

**Comment by jcwillox** [comment]
Hmm, looks like the snapshot took to long to create, there's a 300-second timeout when creating a new backup. If I may ask how big are your full backups normally?

**Comment by poudenes** [comment]
A Full Backup is around 550-600MB in size

**Comment by jcwillox** [comment]
Interesting, that's not particularly big, it works fine with my instance ~150MB. I'll try increasing the timeout to 20 minutes that should fix it.

**Comment by rdeangel** [comment]
Hi, 

my backups are 1.3GB and I get this error (they take about 40 minutes to complete) and I'm getting this error when the backup seem to complete fine.

it would be good to have a way to manually define timeout in the config.

Thanks
