### ISSUE TITLE
Backup not using name data

### ISSUE THREAD

**Issue by mikemor22** [jcwillox/hass-auto-backup#30]
Hello

I hope this isn't old news (although it may) but I haven't found anything mentioning it before:

I installed the addon earlier today and it's working very well, apart one annoying... erm... idiosyncracy; When I run a snapshot, it seems to ignore the 'name' parameter completely, instead giving it a random a character string name.

I tried numerous naming schemes - and even resorted to straight copy/paste from a code example for testing:

service: auto_backup.snapshot_full
data:
&nbsp;&nbsp;name: 'DailyBackup: {{ now().strftime(''%A, %B %-d, %Y'') }}'
&nbsp;&nbsp;keep_days: 14

but still the name is a random string.  Any idea where I'm messing up?

Cheers

**Comment by mikemor22** [comment]
and yes, I'm very unused to writing with inline styling

**Comment by jcwillox** [comment]
Hmm, haven't seen this one before, by random string do you mean like a slug e.g. `11d28993`. That would be quite odd and shouldn't be possible, if the `name` isn't specified Auto Backup will set it to `%A, %b %d, %Y`. I can confirm that it is working correctly (at least for me) on `core-2021.2.3` and `core-2021.3.4`.

You may want to try enabling debug logging for Auto Backup, that way you can see what parameters it is actually receiving.

```yaml
# add this to your configuration.yaml
logger:
  default: warning
  logs:
    custom_components.auto_backup: debug
```

More generally, you may want to check you're running a newish version of Home Assistant and the latest version of Auto Backup, and possibly try reinstalling it.

**Comment by mikemor22** [comment]
Indeed so, it’s exactly that sort of name (I wasn’t aware that was called a slug, so I’ve learned something already).  I should have clarified versions - I’m running core-2021.3.4 on hassos 5.12.  The auto backup was only installed yesterday, so should be a current version.

I’ll see what debug logging gets me, thanks for your help on this.

**Comment by mikemor22** [comment]
Ok, maybe this is just a case of me fundamentally misunderstanding what happens here.  The log shows the snapshot being created (with the specified name in HA) but then the actual data is saved to the compressed file as this ‘slug’. I hadn’t realised this is how things work, I expected the .tar to have the same name, with some sort of suffix for duplicates.
My apologies, I shall slink away and hide in a corner for a bit, until I stop blushing in embarrassment.

**Comment by jcwillox** [comment]
Ahh, that's all good, I thought it might have been that. I totally agree, I always felt that Home Assistant should name the actual snapshot files using the snapshot name. In fact one of my supervisor addons [hassio-rclone-backup](https://github.com/jcwillox/hassio-rclone-backup) adds this functionality by automatically renaming them, it's mainly for syncing snapshots to a cloud provider, where it's quite helpful to have them named like that.

![image](https://user-images.githubusercontent.com/39120423/112648582-c7524780-8e9d-11eb-956a-0632cb533657.png)
