### ISSUE TITLE
It's doesn't work at Home Assistant core-2021.5.5 or 2021.6.4.

### ISSUE THREAD

**Issue by percy10442** [jcwillox/hass-auto-backup#36]
It's doesn't work at Home Assistant core-2021.5.5 or 2021.6.4.
Services are unavailable.

**Comment by jcwillox** [comment]
It's working fine for me on 2021.6.4 and has been on the previous versions too, it might be something to do with your installation, try reinstalling Auto Backup, and making sure it's showing up on the integrations screen (i.e. that you've [setup](https://github.com/jcwillox/hass-auto-backup#configuration) the integration)

**Comment by percy10442** [comment]
OK,I reinstalled Auto Backup and it worked normally.
