### ISSUE TITLE
Error in core-2021.8.0b1

### ISSUE THREAD

**Issue by hvorragend** [jcwillox/hass-auto-backup#37]
Please see breaking changes: https://rc.home-assistant.io/blog/2021/07/28/release-20218/

```
Home Assistant Supervisor
The usage of “snapshot” is deprecated, from now “backup” is used instead.

The service snapshot_full is now named backup_full, the service snapshot_full will be removed in Home Assistant 2021.9.
The service snapshot_partial is now named backup_partial, the service snapshot_partial will be removed in Home Assistant 2021.9.
Using snapshot in the data for the restore_full and restore_partial services is deprecated and will be removed in Home Assistant 2021.9, use slug instead.
```

Error:

```
Logger: homeassistant.setup
Source: setup.py:173 
First occurred: 20:19:22 (1 occurrences) 
Last logged: 20:19:22

Setup failed for auto_backup: Unable to import component: cannot import name 'SCHEMA_SNAPSHOT_FULL' from 'homeassistant.components.hassio' (/usr/src/homeassistant/homeassistant/components/hassio/__init__.py)
```

**Comment by jcwillox** [comment]
This shouldn't break Auto Backup right now as it's not calling the `hassio.snapshot_*` services and is instead making direct calls to the supervisor API, but they have also updated the supervisor API, so it's worth migrating over to those new methods. They've also renamed some of the variables in the hassio component which whats actually breaking Auto Backup. So I've got some work to do 😁.

**Comment by frenck** [comment]
This change will most likely be reverted and postponed to 2021.9

**Comment by frenck** [comment]
@jcwillox As said, the change as been reverted and even for 2021.9, this change you've made: <https://github.com/jcwillox/hass-auto-backup/commit/003e43bb273c8e058e3117f1cd8527ecd94c41f2>

Isn't a fix.

**Comment by jcwillox** [comment]
Looook it may not be a perfect fix, but it does indeed solve the error, identified in this issue, causing Auto Backup to not load, which was that the variable `SCHEMA_SNAPSHOT_FULL` no longer exists, and this is currently still the case (see [homeassistant/components/hassio/__init__.py](https://github.com/home-assistant/core/blob/dev/homeassistant/components/hassio/__init__.py)). So as far as I can tell it is a necessary fix for 2021.8, but yes I'll need to switch to the new API to avoid it breaking in future versions.

**Comment by frenck** [comment]
- It is not needed for 2021.8, as the change has been reverted. It will be part of 2021.9
- Your change fixes an import error, but still will call the deprecated services. Instead, you should do a conditional import. Use SCHEMA_SNAPSHOT_FULL when the import is available, or use SCHEMA_BACKUP_FULL when it's not. That way you are backward and forward compatible.

**Comment by jcwillox** [comment]
Ahh my bad, I see now, I was looking at the dev branch and assuming that was representative of what would be in the release.

Auto Backup doesn't actually make any service calls and uses the Supervisor API directly. I decided against using a conditional import as the two components were almost entirely decoupled and its better that changes to the schema for the `hassio` services shouldn't directly affect Auto Backup.

I'm glad I got a bit more time to make the changes, as this change gave me the motivation to actually refactor the code and especially the API interactions. Anyways, I've done my code cleanup and Auto Backup is now ready for the migration to the new API endpoints, I'll also be following HA in renaming `snapshot` to `backup` for the 2021.9 release. I'll be creating the release supporting 2021.9 closer to the beta.

**Comment by hvorragend** [comment]
Thank you

**Comment by OmgImAlexis** [comment]
@jcwillox any update on this? Updated to 2021.9.3 and this integration no longer loads.

**Comment by jcwillox** [comment]
The integration is working fine for me in 2021.9, make sure you have updated to the latest version of Auto Backup `0.9.2`.

**Comment by OmgImAlexis** [comment]
Yep looks like there wasn’t any update showing until I updated the OS.
