### ISSUE TITLE
problem with download_path

### ISSUE THREAD

**Issue by phptanker** [jcwillox/hass-auto-backup#44]
Hi, been using this tool to backup to an SMB share that I mount in the homeassistant docker image every time it restarts/updates. 

Now when the variable download_path has changed to backup_path the script to run backups doesn't seem to work anymore. 

Here is the trace from HA:
`Stopped because an error was encountered at September 4, 2021, 04:30:00 (runtime: 0.01 seconds) not a directory for dictionary value @ data['download_path']`

Here is my script that I'm trying to run:

> alias: Partial NAS Backup
> icon: mdi:content-save-move-outline
> mode: single
> sequence:
>   - data:
>       download_path: /networkbackup/partial_snapshots
>       name: 'TankerHome_Partial: {{ now().strftime(''%a, %-I:%M %p (%d/%m/%Y)'') }}'
>       keep_days: 30
>     service: auto_backup.backup_partial

Any ideas?

**Comment by jcwillox** [comment]
Hmm, well it really was just a rename of `backup_path` -> `download_path`, so it could be something that Home Assistant changed internally. It seems to be getting caught at the schema validation point where Home Assistant checks if it's actually a directory. So I guess that directory doesn't exist, maybe try it with something you know will exist like `download_path: /share`.

This is the function it's calling to check if it's a directory.
https://github.com/home-assistant/core/blob/dev/homeassistant/helpers/config_validation.py#L237

**Comment by phptanker** [comment]
It was homeassistant that had failed to recognize the mounted share, restarted the HA container once more and now it worked. 

Sorry for jumping the gun but it really seemed like me changing the variable broke the backups since my last functioning one was the night before I changed the variable haha.

**Comment by jcwillox** [comment]
That's all good, glad you got it working again 👍
