### ISSUE TITLE
Does this addon work in HA Core?

### ISSUE THREAD

**Issue by BernieV1977** [jcwillox/hass-auto-backup#47]
Hello,
Does this auto-backup addon work with a Home Assistant Core install with virtual Python  environment on a rpi? (So no Hassio).

Thx
Bernd

**Comment by jcwillox** [comment]
This question has been asked quite a few times, but no it relies heavily on Hassio to create and remove backups and won't even load without it. If you are running Home Assistant like that then you already have easy access to the configuration folder and can use one of the many and probably superior traditional backup solutions anyway.
