### ISSUE TITLE
Error but backup seems to complete.

### ISSUE THREAD

**Issue by antasp3136** [jcwillox/hass-auto-backup#51]
I get this error in the log after the backup seems to complete in the supervisor..

2022-03-14 09:13:36 ERROR (MainThread) [custom_components.auto_backup] Error during backup. Unknown error, see supervisor. There may be a backup already in progress.

**Comment by jcwillox** [comment]
So I can tell the supervisor is actually returning an error to auto backup, but I don't know why. Do the supervisor logs show any errors? Could you also post the service call you used and possibly anything relevant from the supervisor log?

**Comment by jcwillox** [comment]
This is very likely a timeout issue, the timeout can be increased in the options menu, but  Auto Backup can become unreliable with backups that take a long time to complete (an unfortunate limitation of how Home Assistant implemented their backup API).
