### ISSUE TITLE
Problem adding Auto Backup

### ISSUE THREAD

**Issue by DirkStorck** [jcwillox/hass-auto-backup#52]
Hi,

if I try to add "Auto Backup" 

![grafik](https://user-images.githubusercontent.com/2306190/162066950-dbcc2a37-a5d7-49ee-b257-6483d0c0b3e0.png)

I get this error message saying that Haas.io isn't installed 
![grafik](https://user-images.githubusercontent.com/2306190/162067043-1f1612bd-6c24-4d5a-9bda-918dc98021b0.png)

I have installed "Home Assistant" through a docker image.

Any advice please!

Thank you!

**Comment by jcwillox** [comment]
Auto Backup has always required the Home Assistant Supervisor to work, as it is what actually performed the backups. Now that Home Assistant supports this without the Supervisor it's likely that Auto Backup can be made to work without it as well, see issue #53.

**Comment by DirkStorck** [comment]
Thank you. Will have a look :)

**Comment by jcwillox** [comment]
Support for Home Assistant Core was added in [1.0.0](https://github.com/jcwillox/hass-auto-backup/releases/tag/1.0.0) 🎉
