### ISSUE TITLE
Plan to support Home Assistant Core/Docker backup?

### ISSUE THREAD

**Issue by tuanha2000vn** [jcwillox/hass-auto-backup#53]
Hi there.

The new version Home Assistant 2022.4.0 support backup if you run Home Assistant Core in Python or use a Home Assistant Container in Docker.

Can you please make this addon support that?

Thank you.

**Comment by jcwillox** [comment]
Oh very cool, seems doable, I'll start looking into it.

**Comment by jayakornk** [comment]
Can't wait to use this integration!

**Comment by jcwillox** [comment]
Support for Home Assistant Core was added in [1.0.0](https://github.com/jcwillox/hass-auto-backup/releases/tag/1.0.0) 🎉
