### ISSUE TITLE
Does this Work with new backup feature in 2022.4?

### ISSUE THREAD

**Issue by bobbowitch** [jcwillox/hass-auto-backup#56]
Just wondering if this will work with the new backup feature in Core and Container installs, introduced in 2022.4?

**Comment by jcwillox** [comment]
Yes it does, there a couple of limitations running with Home Assistant Core vs Supervised, the [docs](https://jcwillox.github.io/hass-auto-backup/home-assistant-core) have more info.

**Comment by bobbowitch** [comment]
Tyvm
