### ISSUE TITLE
Support multiple download locations

### ISSUE THREAD

**Issue by jcwillox** [jcwillox/hass-auto-backup#58]
### Discussed in https://github.com/jcwillox/hass-auto-backup/discussions/42

<div type='discussions-op-text'>

<sup>Originally posted by **itbeemer** August 29, 2021</sup>
Good afternoon,
Is it possible to have this add-in use multiple download locations?
I am using HA on an RPi.  I would like to have to go to the normal backups folder, a usb stick locally connected to the RPi, and to a samba share.  (for redundancy)

Thanks much!
Barak</div>

**Comment by jcwillox** [comment]
This feature has been added in version [1.1.0](https://github.com/jcwillox/hass-auto-backup/releases/tag/1.1.0) 🎉

**Comment by itbeemer** [comment]
Thank-you for adding this.  I will be testing it out shortly.
Have a great day!
Barak
