### ISSUE TITLE
Ability to set backup name as filename

### ISSUE THREAD

**Issue by l-t-k** [jcwillox/hass-auto-backup#60]
I would like to have an option to change the filename on disk of each backup. Right now we can set a custom name for each backup, but this does not change the filename on disk.

I know your other add-on (hassio-rclone-backup) have this option (#30 ), but I'm using my own setup to move my backups away from the host: Syncthing syncs my backups with my desktop pc. It would be very useful if I receive backups on my desktop with explanatory filenames instead of the slug. 

Oh, and this add-on is awesome :) 
I really like it, this enhancement will make it perfect for me

**Comment by jcwillox** [comment]
Thanks! Sorry I didn't see this earlier, but that's actually not possible, integrations (like Auto Backup) literally do not have access to the `/backup` folder on your system, meaning the only way we can interact with them is via the Home Assistant Supervisor API. This means we can't change the name of the backups on the disk, among many other frustrating limitations. This is not the case for addons (like hassio-rclone-backup), which can request direct access to the backup folder.

> It would be very useful if I receive backups on my desktop with explanatory filenames instead of the slug.

I agree Home Assistant should really use more friendly names by default when writing backups to the filesystem.
