### ISSUE TITLE
HA 2022.07 error

### ISSUE THREAD

**Issue by leonardpitzu** [jcwillox/hass-auto-backup#61]
Home Assistant 2022.07 beta brings about a new error pointing to `handler.py` line 11 (from `homeassistant.components.hassio.const import X_HASSIO`)

the error message is:
`Setup failed for custom integration auto_backup: Unable to import component: cannot import name 'X_HASSIO' from 'homeassistant.components.hassio.const' (/usr/src/homeassistant/homeassistant/components/hassio/const.py)`

Edit: the change from the `core` repository https://github.com/home-assistant/core/commit/eac7c5f177bf5702fb42a4eab49de348c9e32f40

**Comment by alexruffell** [comment]
Same error here. Full error text is:
```
Logger: homeassistant.setup
Source: setup.py:162
First occurred: 16:08:53 (1 occurrences)
Last logged: 16:08:53

Setup failed for custom integration auto_backup: Unable to import component: cannot import name 'X_HASSIO' from 'homeassistant.components.hassio.const' (/usr/src/homeassistant/homeassistant/components/hassio/const.py)
```

**Comment by spry-salt** [comment]
Ditto

**Comment by jcwillox** [comment]
Thanks for catching this, I knew it was going to happen eventually, but thought there'd be more warning. This issue should be fixed in version [1.1.0](https://github.com/jcwillox/hass-auto-backup/releases/tag/1.1.0).

**Comment by leonardpitzu** [comment]
Thanks for fixing the issue. Is back working again.

**Comment by spry-salt** [comment]
Thank you.
