### ISSUE TITLE
Add the ability to include/exclude multiple addons at once

### ISSUE THREAD

**Issue by l-t-k** [jcwillox/hass-auto-backup#66]
First of all, and probably again, really appreciate your work for bringing the community this must have addon!

I'm running a lot of addons on my hassio machine that can be placed in 'buckets': core (dns, dhcp etc.), personal (synchting, wireguard) and multimedia (sonarr, nzbget). I would like to keep all the multimedia addons away from my core backups, because they massively increase the size of the backup and I want to run and keep less frequent backups for those addons. However, I'm running a lot of those and they also change by adding new or removing old multimedia addons very rapidly. 

All of the multimedia addons installed are from a single repository. Therefore they all have the same prefix in their docker name. For example all the core addons start with addon_core_*. I would like to have the ability to exclude (or include) all of those addons from a certain repo at once. Like so:
```
include_addons:
  - addon_core_*
```

If that is possible I don't have to check and reassign my backups every time I'm adding a addon.

**Comment by jcwillox** [comment]
Thanks! This is a great idea, I never thought about it like that but it would make a good addition 👍

**Comment by jcwillox** [comment]
This feature has been added in version [1.2.0](https://github.com/jcwillox/hass-auto-backup/releases/tag/1.2.0) 🎉
