### ISSUE TITLE
Cant restart HA

### ISSUE THREAD

**Issue by celeroll** [jcwillox/hass-auto-backup#72]
I have problems to restart HA. 
Configuration check shows this error:
Component error: auto_backup - cannot import name 'PATCH_NAME' from 'custom_components.auto_backup.const' (/config/custom_components/auto_backup/const.py)

**Comment by jcwillox** [comment]
That error shouldn't be possible, my best guess is the installation is broken, perhaps try reinstalling from HACS, or force restarting Home Assistant.

**Comment by celeroll** [comment]
Thanks for the hints. Reinstalling didn't help, because it is asking about "restart HA" and that was not possible due to above error. I have forced restarted my VM and now everything is fine. I was just not able to restart HA from UI.
