### ISSUE TITLE
Backup error

### ISSUE THREAD

**Issue by FritsOV** [jcwillox/hass-auto-backup#74]
I guess its a simple error but as newbi not so simple
I keep getting an error on mosquitto broker and sometimes mariadb

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.auto_backup
Source: custom_components/auto_backup/__init__.py:187
Integration: Auto Backup (documentation, issues)
First occurred: 00:00:00 (6 occurrences)
Last logged: 12:00:00

Addon 'core-mosquitto' does not exist
Addon 'core-mariadb' does not exist

In my automation i took the sample wich is provided:

service: auto_backup.backup_partial
data:
  name: "AutoBackup:  {{ now().strftime('%a, %-I:%M %p (%d/%m/%Y)') }}"
  addons:
    - core-mosquitto
    - core-mariadb
  folders:
    - homeassistant
    - ssl
    - share
  keep_days: 2

What am i doing wrong?

Kind regards,
Frits

**Comment by jcwillox** [comment]
I believe the issue is that you used a `-` instead of an `_` for the addon slugs, e.g. `core-mosquitto` should be `core_mosquitto`. Alternatively, you can also use the addon name and Auto Backup will automatically retrieve the slug for it, so `MariaDB` or `Mosquitto broker` should also work.
