### ISSUE TITLE
Documentation doesn't include any guide on restoring

### ISSUE THREAD

**Issue by mcclumpherty** [jcwillox/hass-auto-backup#79]
### The problem

This looks like a really great add-on, but it would be really helpful if you could update the documentation to include a description of how to do a restore from a backup.

### What version of Auto Backup has the issue?

1.3.0

### What version of Home Assistant are you running?

n/a

### What type of installation are you running?

Home Assistant OS

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

2022.11.2

**Comment by jcwillox** [comment]
You just restore through the normal home assistant web interface (or follow their restoration instructions). Auto Backup just automates the process of telling the supervisor to create a backup and to delete them.

Unless you mean un-delete them which you can, without using data recovery tools.

**Comment by mcclumpherty** [comment]
Great stuff - many thanks !
