### ISSUE TITLE
Not all folders are being backed in 

### ISSUE THREAD

**Issue by reesion** [jcwillox/hass-auto-backup#8]
Hi,

I noticed that not all folders are being backed up when using auto_backup.snapshot_full

The folders in particular are www and themes folders in the root of /config/.

Below are my configurations in automation.yaml

Am i missing anything?

  - alias: Perform Daily Backup
    trigger:
      - platform: time
        at: "00:00:00"
    action:
      - service: auto_backup.snapshot_full
        data_template:
          name: "DailyBackup: {{ now().strftime('%A, %B %-d, %Y') }}"
          keep_days: 7

**Comment by jcwillox** [comment]
Hey, your automation looks fine to me. If your configuration folder is being backed up, but some folders inside the configuration directory are not, then this is likely an issue with Home Assistant. AutoBackup has no way of excluding specific folders inside the `/config/` directory, and Hass.io is responsible for creating the actual snapshot.

Can you try taking a full backup via the supervisor snapshots page in the web UI and see if that snapshot includes the missing folders?

**Comment by reesion** [comment]
My manual backup contains the missing folders. 

This came to my attention because of the backup size. My manual backup size are way larger.

**Comment by jcwillox** [comment]
Right. When you create the full snapshots with AutoBackup do they show up on the snapshots page, if they do what do they show up as full or partial snapshots? and do they show the config as backed up?

**Comment by reesion** [comment]
Yes, they do show up in the snapshot page as full. 

However the backup from autobackup is not showing the HA configuration

**Comment by jcwillox** [comment]
Probably should've asked this originally but can you post any logs related to the supervisor, Hass.io or Auto Backup when taking a full snapshot (and having this issue occur). Does this issue occur reliably whenever you do a full snapshot? 

Are there any issues with partial snapshots such as the following?
Call the service: `auto_backup.snapshot_partial`
Service Data:
```yaml
name: Test
folders:
  - homeassistant
keep_days: 0.00001
```

If the logs don't show anything you can also try checking you're on the latest version of Home Assistant and Auto Backup or try reinstalling Auto Backup.

**Comment by reesion** [comment]
I've just done a few more testing and found out the full snapshot sometimes includes the ha configurations.

Partial snapshots only backs up the home assistant (if i use the settings that you've provided earlier)

Can't seem to find anything related in the logs.

**Comment by jcwillox** [comment]
So, I can't seem to reproduce this issue.
How large are your manual full backups? And how large is your configuration directory?

The partial snapshot example above should only backup up the HA config folder. Just confirming the partial snapshot is properly backing up your www and themes folders, and the full snapshot does not?

**Comment by reesion** [comment]
The manual full backups is approximately 52.9MB and the homeassistant folder is approximately 288MB.

The partial backup does not contain the www and themes folders at times.  Everything is hit and miss. 

So everything is just random  - at times i will get no missing folders.
