### ISSUE TITLE
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups

### ISSUE THREAD

**Issue by gateriderz** [jcwillox/hass-auto-backup#83]
### The problem

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for auto_backup using this method at custom_components/auto_backup/__init__.py, line 192: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

Reproduction steps
1.restart ha
2. check log

### What version of Auto Backup has the issue?

1.3.0

### What version of Home Assistant are you running?

Home Assistant 2023.2.0b3

### What type of installation are you running?

Home Assistant OS

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

Supervisor 2023.01.1

### Example YAML snippet

```yml
...
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    return True
...
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

**Comment by jcwillox** [comment]
Thanks, this has been fixed in https://github.com/jcwillox/hass-auto-backup/releases/tag/1.3.1
