### ISSUE TITLE
Auto Backup Reboot Home Assistant

### ISSUE THREAD

**Issue by guarddog13** [jcwillox/hass-auto-backup#90]
### The problem

I have my auto backups set to run every night at 4am. When they complete Home Assistant restarts every time. 

### What version of Auto Backup has the issue?

1.3.1

### What version of Home Assistant are you running?

2023.3.1

### What type of installation are you running?

Home Assistant Container

### Anything in the logs that might be useful for us?

```python3
I have the logger set to this and don't see anything in the logs that would show a reason for it to be restarting after every backup.
```

**Comment by jcwillox** [comment]
Hmm not sure there's much I can do about this, sounds like an issue with HA if anything, there's not much Auto Backup can do to make it crash especially without generating any logs, maybe it's very large and is causing the process to crash.
